### PR TITLE
Fix cross-site tab alignment and appearance.

### PR DESCRIPTION
**Pull request by leftclickben**
- Align inside container (in line with logo).
- Adjust paddings and margins to fix alignment.
- Adjust colours for consistency with other sites.
- Adjust border-radius for consistency with other sites.

### CODE REVIEW

**Comment by leftclickben** [comment]
@mostro20 had a go and found it was fixable with CSS only, and adding a class to one of the wrapper elements.

**Comment by leftclickben** [comment]
Importantly I didn't have to deal with `layout/default.xml`.

**Comment by leftclickben** [comment]
BTW this is visible in staging having been deployed bypassing git.

**Comment by mostro20** [comment]
Nice. Thanks for that. Bypassing layout.xml is good. About to enter that dreamworld with the accounts links later today. But this is looking good :-)

**Pull request merged**
